### ISSUE TITLE
Initial Assessment for Scheduler Plugin

### ISSUE THREAD

**Issue by cmisale** [flux-framework/flux-k8s#1]
As discussed during our meeting on Feb 3rd, we have two main options to build the Fluxion Scheduler Plugin

1. Extension Points (Scheduling Framework)
2. Out-of-tree Scheduler Plugin

We would need to start a discussion about pros/cons of the two options, so that we can take a decision ASAP.
Initial metrics we can consider are:
- Maintainability wrt Kubernetes/OpenShift releases
- Ease of implementation and deployment in Kubernetes/OpenShift
- Ease of integration with Fluxion 
- What else? 

Regardless of the option we go for, there are certain tasks we have to address that we identified during our discussion:
- Implement a Golang binding for [Fluxion C CLI](https://github.com/flux-framework/flux-sched/tree/master/resource/hlapi/bindings/c)
- Define where/how to save state for Fluxion (i.e., Resource Graph)
  - Define what's the minimal state that we need
  - How the state is shared/accessed in case of hierarchical instances
- Talk about how to access information about NFD in the future

**Comment by milroy** [comment]
I'm going to create issues for each of the tasks you define here so we can track them separately.

**Comment by milroy** [comment]
I've opened several derived issues based on this one.  Have I missed anything?

@cmisale: let's limit this issue to a discussion of the pros and cons of making use of the Scheduling Framework versus an out-of-tree scheduler plugin approach.  Does that sound reasonable?

**Comment by swatisehgal** [comment]
Please refer to the link [here](https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/624-scheduling-framework#custom-scheduler-plugins-out-of-tree) which describes how the scheduler plugin allows us to write a custom scheduler without forking the scheduler's code. The scheduler-plugins repo here: https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/cmd/scheduler/main.go is an example of a custom scheduler. So essentially in your above issue description where you mention building Fluxion Scheduler Plugin either with the scheduler framework or as an out of tree scheduler plugin please keep in mind that you could use both and develop **a customized out-of-tree scheduler plugin that uses the scheduler framework**!

**Comment by dongahn** [comment]
Oh this is a great resource, @swatisehgal! Thank you for chiming in.

**Comment by vsoch** [comment]
We have a fairly good strategy here, so I'm going to close this issue. Great job to everyone here for the work on this!
