### ISSUE TITLE
Problems compiling when running `make`

### ISSUE THREAD

**Issue by kannon92** [flux-framework/flux-k8s#36]
I have cloned the repo and I am trying to build the scheduler plugin.  

a) cd scheduler-plugin
b) `make`

I get the following error in the build:

```
make[1]: Leaving directory '/home/flux-sched'
cp: cannot stat 'resource/hlapi/bindings/c/.libs/*': No such file or directory
The command '/bin/sh -c git clone https://github.com/cmisale/flux-sched.git --branch gobind-dev --single-branch &&     cd /home/flux-sched/ 	&& ./autogen.sh && PYTHON_VERSION=3.8 ./configure --prefix=/home/flux-install && make -j && make install 	&& cp -r resource/hlapi/bindings/c/.libs/* resource/.libs/* /home/flux-install/lib/ 	&& cp -r resource/hlapi/bindings/go/src/fluxcli /go/src/ 	&& mv  resource/hlapi/bindings /tmp 	&& cd /home && mkdir -p flux-sched/resource/hlapi && mv /tmp/bindings flux-sched/resource/hlapi' returned a non-zero code: 1
```

I think this is an issue in the `Dockerfile`:

```
	&& cp -r resource/hlapi/bindings/c/.libs/* resource/.libs/* /home/flux-install/lib/ \
	&& cp -r resource/hlapi/bindings/go/src/fluxcli /go/src/ \
```

Any suggestions on how to proceed?

**Comment by vsoch** [comment]
@milroy and @cmisale can comment but I think you probably want the canopie-artifacts22 branch https://github.com/flux-framework/flux-k8s/tree/canopie22-artifacts  or the associated release https://github.com/flux-framework/flux-k8s/releases/tag/v1.0.1

**Comment by kannon92** [comment]
> @milroy and @cmisale can comment but I think you probably want the canopie-artifacts22 branch https://github.com/flux-framework/flux-k8s/tree/canopie22-artifacts or the associated release https://github.com/flux-framework/flux-k8s/releases/tag/v1.0.1

Ah thank you.  I checked out this branch but I also found this README for the PI one and that seems to work. (https://github.com/flux-framework/flux-k8s/tree/main/examples/pi)

**Comment by vsoch** [comment]
Oh I remember that one! @ArangoGutierrez showed me that a long time ago. Hi @ArangoGutierrez :wave: thanks for the pie! :pie:

**Comment by ArangoGutierrez** [comment]
That PI project just keeps giving :)

**Comment by cmisale** [comment]
@kannon92 to build and install the plugin scheduler, you will need to refer to the fork of the scheduler framework we have in [here](https://github.com/openshift-psap/scheduler-plugins/tree/fluence) (branch fluence). We follow the same methodology and infrastructure used by the framework and therefore:

-  if you want to build the container, then: 
```bash
make local-image
% docker tag && docker push
```

- if you want to install the plugin, then refer to the [README](https://github.com/openshift-psap/scheduler-plugins/tree/fluence/manifests/install/charts/as-a-second-scheduler) to install the plugin using Helm. `values.yaml` file can be customized


I hope it still works.. I don't have any place where to try it for now

**Comment by kannon92** [comment]
Sorry, @cmisale notes helped me to play around with fluxion in Armada. We were able to use the plugin for an Armada job. We didn’t pursue it much farther than that.

I am afraid I am no longer involved with Armada so I won’t be able to continue this line of work.

We can close this issue for now.
