### ISSUE TITLE
feat: Update fluxion with changes to K8s graph

### ISSUE THREAD

**Issue by milroy** [flux-framework/flux-k8s#4]
This issue originates from the items @cmisale brought up in issue #1.

How can hierarchical Flux-K8s instances access the resource graph?  Claudia, can you expand on this question a bit?  I didn't fully understand your idea during our discussion.

**Comment by vsoch** [comment]
I think the answer here is that we generate the Fluxion JGF (json format of the graph) based on an initial node listing. What we don't support is updates to that. I'm going to rescope this issue to be about that.

**Comment by vsoch** [comment]
I think this was probably answered and is safe to close. @cmisale please reopen if you want to continue discussion!
